name: homedeals
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_size_text: any
  google_fonts: any
  get: any
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  image_picker: any
  file_selector: ^1.0.3
  firebase_auth: ^5.2.0
  firebase_storage: 12.1.3
  firebase_core: 3.4.0
  fl_chart:
  dio: ^5.5.0+1
  jwt_decoder:
  syncfusion_flutter_sliders: 26.2.10
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  cached_network_image: 3.4.0
  google_maps_flutter_web: ^0.5.10
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  dropdown_button2: ^2.3.9
  flutter_dotenv: ^5.2.1
  go_router: ^14.8.0
  multi_dropdown: ^3.0.1
  country_state_city: ^0.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  analyzer: ^4.7.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - .env
     - assets/images/
     - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
