// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATj4i6bZLTUjSPE49ivFrzGQCT9hv1A4A',
    appId: '1:495252039954:web:a62f9eeffa3d755f572bcb',
    messagingSenderId: '495252039954',
    projectId: 'homedeals-d6dec',
    authDomain: 'homedeals-d6dec.firebaseapp.com',
    storageBucket: 'homedeals-d6dec.appspot.com',
    measurementId: 'G-5MEQ7TJG18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXKogjCYBFxY6xP2KSZaF1DawO9fpm9oA',
    appId: '1:495252039954:android:8a1a55ec333ed20b572bcb',
    messagingSenderId: '495252039954',
    projectId: 'homedeals-d6dec',
    storageBucket: 'homedeals-d6dec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsOCknQyVtdtXED9CA09K6Sjyu3yBT21U',
    appId: '1:495252039954:ios:ceb10f82c9bf671b572bcb',
    messagingSenderId: '495252039954',
    projectId: 'homedeals-d6dec',
    storageBucket: 'homedeals-d6dec.appspot.com',
    iosBundleId: 'com.homedeals.homedeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsOCknQyVtdtXED9CA09K6Sjyu3yBT21U',
    appId: '1:495252039954:ios:ebc4251384e401d6572bcb',
    messagingSenderId: '495252039954',
    projectId: 'homedeals-d6dec',
    storageBucket: 'homedeals-d6dec.appspot.com',
    iosBundleId: 'com.homedeals.homedeals.RunnerTests',
  );
}
